# DOC https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html#collections-galaxy-meta
---
namespace:      wucenter
name:           wucenter
version:        0.0.1
readme:         README.md
authors:        wucenter at elias dot la
description:    VMware vCenter Ubuntu VMs
license:        [WTFPL, MIT]
tags:           [vmware, vsphere, vcenter, ubuntu, bionic, iac, gitops]
documentation:  https://github.com/wucenter/wucenter-ansible
repository:     https://github.com/wucenter/wucenter-ansible
homepage:       https://github.com/wucenter/wucenter-ansible
issues:         https://github.com/wucenter/wucenter-ansible/issues
dependencies:
  ansible.netcommon:  "*"
  community.general:  "*"
  community.vmware:   "*"
