---

- name: Checks  | Required credentials
  when: (var_item not in vars) or (var_item is none) or (var_item | trim == '')
  loop_control:
    loop_var: var_item
  loop:
  - vcenter_host
  - vcenter_dc
  - vcenter_user
  - vcenter_pass
  - template_name
  - template_user
  - template_pass
  - robops_user
  - robops_pass
  - ops_user
  - ops_pass
  - ops_sshk
  fail:
    msg: "{{ var_item }} key is not defined in credentials/*.yml supported files"
