---

- when:
  - ( state is not defined ) or ( state != 'absent' )
  - vm_auto | default([]) | intersect(['auto', 'auto/all', 'auto/manage', 'auto/bury'])
  - lookup('env', 'NO_BURY') | length == 0
  import_tasks: bury_vc_meta.yml
