---

- name: Checks  | Role required variables
  fail: msg="{{ var_item }} is not defined"
  when: (var_item is not defined) or (var_item is none) or (var_item | trim | length == 0)
  loop_control:
    loop_var: var_item
  loop:
    - vcenter_host
    - vcenter_dc

    - vcenter_user
    - vcenter_pass

    - robops_user
    - robops_pass

    - vm_name
    # - vm_folder

    - vmware_vm_lineinfile_data
    - vmware_vm_lineinfile_path
    # - vmware_vm_lineinfile_info
