#!/usr/bin/env -S ansible-galaxy role install --verbose --roles-path roles_galaxy/ --force --force-with-deps --role-file
---

# TIP Declare third-party roles

roles:

  # SAMPLE: from Galaxy
  # - name:     geerlingguy.docker
  #   version:  2.7.0

  # SAMPLE: from GitHub
  # - src:      https://github.com/bennojoy/nginx

  # SAMPLE: from GitHub, overriding the name and specifying a specific tag
  # - name:     nginx_role
  #   src:      https://github.com/bennojoy/nginx
  #   version:  master

  # SAMPLE: from GitLab or other git-based scm
  # - src:      git@git.domain.tld:path/ansible-roles.git
  #   scm:      git
  #   version:  "0.1"  # TIP quoted, so YAML doesn't parse this as a floating-point value

  # SAMPLE: from Bitbucket
  # - src:      git+http://bitbucket.org/willthames/git-ansible-galaxy
  #   version:  v1.4

  # SAMPLE: from a webserver, where the role is packaged in a tar.gz
  # - name:     http-role
  #   src:      https://some.webserver.example.com/files/master.tar.gz
