---

- name: "vSphere | Align CPU"
  delegate_to:                  localhost
  register:                     info
  vmware_guest:                 # DOC https://docs.ansible.com/ansible/latest/modules/vmware_guest_module.html
    force:                      true
    validate_certs:             false
    state:                      present
    username:                   "{{ vcenter_user }}"
    password:                   "{{ vcenter_pass }}"
    hostname:                   "{{ vcenter_host }}"
    datacenter:                 "{{ vcenter_dc }}"
    name:                       "{{ vm_name }}"
    folder:                     "{{ vm_folder }}"
    hardware:
      num_cpus:                 "{{ vm_cpu }}"
      # num_cpu_cores_per_socket: "{{ ( vm_cpu / 2 ) | round(0,'floor') | int }}"
