---

- name: "vSphere | Power-off VMs"
  delegate_to:                  localhost
  register:                     info
  vmware_guest_powerstate:      # DOC https://docs.ansible.com/ansible/latest/modules/vmware_guest_powerstate_module.html
    validate_certs:             false
    username:                   "{{ vcenter_user }}"
    password:                   "{{ vcenter_pass }}"
    hostname:                   "{{ vcenter_host }}"
    name:                       "{{ vm_name }}"
    folder:                     "{{ vm_folder }}"
    state:                      powered-off
