---

- name: Checks  | Role required variables
  fail: msg="{{ var_item }} is not defined"
  when: (var_item not in vars) or (var_item is none) or (var_item | trim == '')
  loop_control:
    loop_var: var_item
  loop:
    - vm_roles

    - ops_sshk

    - ansible_host
    - ansible_user
    - ansible_sudo_pass
    - ansible_os_family
    - ansible_distribution
    - ansible_distribution_release
