#!./wucenter_player.sh --vault
---

- import_playbook: init.yml



- name: Scan vCenter VMs
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"
  roles:
  - wucenter_scan_mini



- name: Decommission vCenter VMs
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"
  vars:
    ansible_play:               decommission
  roles:
  - wucenter_decommission



- name: Rename vCenter VMs
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"
  - "{{ wucenter_basedir }}credentials/robops.yml"
  vars:
    ansible_play:               rename
  roles:
  - wucenter_rename



- name: Provision vCenter VMs
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"
  - "{{ wucenter_basedir }}credentials/template.yml"
  - "{{ wucenter_basedir }}inventory/users.yml"
  vars:
    ansible_play:               provision
    robops_user:                "{{ template_user }}"
    robops_pass:                "{{ template_pass }}"
  roles:
  - wucenter_provision



- name: Align vCenter VMs
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"
  - "{{ wucenter_basedir }}credentials/robops.yml"
  - "{{ wucenter_basedir }}inventory/users.yml"
  vars:
    ansible_play:               align
  roles:
  - wucenter_align



- name: Play tagged roles
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"     # DEV for burying
  - "{{ wucenter_basedir }}credentials/ops.yml"
  - "{{ wucenter_basedir }}inventory/users.yml"
  vars:
    ansible_play:               apps
  roles:
  - wucenter_roles
