#!./wucenter_player.sh --vault --no-deps --no-ipam
---

- import_playbook: init.yml

- name: Deploy Apps
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"     # DEV for burying
  - "{{ wucenter_basedir }}credentials/ops.yml"
  - "{{ wucenter_basedir }}inventory/users.yml"
  vars:
    ansible_play:               apps
  roles:
  - wucenter_roles
