#!./wucenter_player.sh
---

- name: Init Framework 1/2
  hosts:                        localhost
  gather_facts:                 false
  tasks:
  - name:
    when: ( wucenter_basedir is not defined ) or ( lookup('fileglob', wucenter_basedir+'/ansible.cfg') | trim == '' )
    fail:
      msg: "Missing required configuration variable: wucenter_basedir"
  - setup:



- name: Init Framework 2/2
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"
  - "{{ wucenter_basedir }}credentials/robops.yml"
  - "{{ wucenter_basedir }}credentials/ops.yml"
  - "{{ wucenter_basedir }}credentials/template.yml"
  roles:
  - wucenter_init



# TODO create dedicated role: init_inventory
- name: Init Inventory
  hosts:                        localhost,vms  # DEV: for pushing `inventory_vm_*` into localhost hostvars
  gather_facts:                 false
  serial:                       1  # DEV HACK: localhost accumulator
  tasks:
  - name: Facts   | Inventory Names & IPs
    delegate_to:                localhost
    delegate_facts:             true
    when:
    - inventory_hostname != 'localhost'
    - state is not defined or state != 'absent'
    - vm_name is defined
    - vm_net_ip is defined
    set_fact:                   # DEV HACK: localhost accumulator
      inventory_vm_names:       "{{ hostvars.localhost.inventory_vm_names   | default([]) + [ vm_name ] }}"
      inventory_vm_net_ips:     "{{ hostvars.localhost.inventory_vm_net_ips | default([]) + [ vm_net_ip ] }}"
