#!./wucenter_player.sh
---

- name: Init Framework 1/2
  hosts:                        localhost
  gather_facts:                 false
  tasks:
  - name:
    when: ( wucenter_basedir is not defined ) or ( lookup('fileglob', wucenter_basedir+'/ansible.cfg') | trim == '' )
    fail:
      msg: "Missing required configuration variable: wucenter_basedir"
  - setup:



- name: Init Framework 2/2
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"
  - "{{ wucenter_basedir }}credentials/robops.yml"
  - "{{ wucenter_basedir }}credentials/ops.yml"
  - "{{ wucenter_basedir }}credentials/template.yml"
  roles:
  - wucenter_init



# TODO create dedicated role: init_
- name: Init Inventory
  hosts:                        localhost,vms  # DEV: for pushing `ansible_play_hosts_all` into localhost hostvars
  gather_facts:                 false
  # collections:
  # - community.general  # TOCHECK json_query
  tasks:
  - name: Facts   | Inventory Names & IPs
    run_once: true
    set_fact:
      inventory_vm_names:       "{{ ansible_play_hosts_all | reject('==', 'localhost') | map('extract', hostvars, []) | list | json_query('[?state!=`absent`].vm_name') }}"
      inventory_vm_net_ips:     "{{ ansible_play_hosts_all | reject('==', 'localhost') | map('extract', hostvars, []) | list | json_query('[?state!=`absent`].vm_net_ip') }}"
# BUG: ansible_play_hosts_all will not get duplicate names IF YAML inventory colliding name keys are in different folders, latest key definition will override previous
