#!./wucenter_player.sh --vault --no-deps --no-role --no-ipam
---

- import_playbook: init.yml

- name: Scan vCenter VMs
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"
  - "{{ wucenter_basedir }}credentials/robops.yml"
  vars:
    ansible_play:               scan
  roles:
  - wucenter_scan_mini
  - wucenter_scan_full
