#!./wucenter_player.sh --vault --no-auto
---

- import_playbook: init.yml

- name: Gather available APT updates
  hosts:                        vms
  gather_facts:                 false
  collections:
  - wucenter.wucenter
  vars_files:
  - "{{ wucenter_basedir }}credentials/vcenter.yml"
  - "{{ wucenter_basedir }}credentials/robops.yml"
  roles:
  - wucenter_scan_mini
  - wucenter_updates
