---

# DOC: Appends to `scan_vm`


- name: vSphere | Query VMs for Disk & Swap info
  delegate_to:                  localhost
  register:                     disk_info
  vmware_guest_disk_info:       # DOC https://docs.ansible.com/ansible/latest/modules/vmware_guest_disk_info_module.html
    validate_certs:             false
    username:                   "{{ vcenter_user }}"
    password:                   "{{ vcenter_pass }}"
    hostname:                   "{{ vcenter_host }}"
    datacenter:                 "{{ vcenter_dc }}"
    name:                       "{{ vm_name }}"
    # folder:                     "{{ vm_folder }}"



- name: Facts   | Parse Disk info
  when:
  - disk_info is not none
  - "'guest_disk_info' in disk_info"
  - "'0' in disk_info.guest_disk_info"
  set_fact:
    temp_vm:
      vm_disk:                  "{{ ( disk_info.guest_disk_info['0'].capacity_in_bytes /1024/1024 ) | round(0,'floor') | int }}"
      # vm_disk_reserved:         "{{ disk_info.guest_disk_info['0'].backing_thinprovisioned | bool }}"



- name: Facts   | Merge Disk info
  when:                         temp_vm is defined
  set_fact:
    scan_vm:                    "{{ scan_vm | combine(temp_vm) }}"
    temp_vm:



- name: Facts   | Parse Swap info 1/2
  when:
  - disk_info is not none
  - "'guest_disk_info' in disk_info"
  - "'1' in disk_info.guest_disk_info"
  set_fact:
    temp_vm:
      vm_swap:                  "{{ ( disk_info.guest_disk_info['1'].capacity_in_bytes /1024/1024 ) | round(0,'floor') | int }}"



- name: Facts   | Parse Swap info 2/2
  set_fact:
    temp_vm:
      vm_swap:                  "0"
  when:
  - (disk_info is none) or ('guest_disk_info' not in disk_info) or ('1' not in disk_info.guest_disk_info)



- name: Facts   | Merge Swap info
  set_fact:
    scan_vm:                    "{{ scan_vm | combine(temp_vm) }}"
    temp_vm:
  when:
  - temp_vm is defined
