---

- import_tasks:                 wucenter_init_ids.yml
- import_tasks:                 wucenter_init_defaults.yml

- block:

  - import_tasks:               wucenter_init_ip.yml
  - import_tasks:               wucenter_init_glue.yml
  - import_tasks:               check_vars.yml

  when: ( state is not defined ) or ( state != 'absent' )
