---

- name: Checks  | VM state
  vars:
    state_supported_values:
    - absent
  when:
  - state is defined
  - state not in state_supported_values
  fail:
    msg: "Invalid state value '{{ state }}' for host '{{ vm_name }}'"



- name: Checks  | VM name
  when:
  - ( '.' not in inventory_hostname )
  - (vm_name is not defined) or (vm_name | trim == '') or ('.' not in vm_name)
  - (vm_net_sd is not defined) or (vm_net_sd | trim == '')
  fail:
    msg: "Cannot compute FQDN for VM: {{ inventory_hostname }}"



- name: Facts   | VM name 1/3
  when:
  - vm_name is defined
  - vm_name | trim != ''
  - ( '.' not in vm_name )
  set_fact:
    vm_name: "{{ vm_name }}.{{ vm_net_sd }}"



- name: Facts   | VM name 2/3
  when:
  - (vm_name is not defined) or (vm_name | trim == '')
  - ( '.' not in inventory_hostname )
  set_fact:
    vm_name: "{{ inventory_hostname }}.{{ vm_net_sd }}"



- name: Facts   | VM name 3/3
  when:
  - (vm_name is not defined) or (vm_name | trim == '')
  - ( '.' in inventory_hostname )
  set_fact:
    vm_name: "{{ inventory_hostname }}"
